-- Intentionally empty.
-- This migration was generated as a destructive drop for Product Ops tables before the SQL-backed
-- Product Ops create migration was added. Leaving it as a no-op keeps migration ordering stable
-- while allowing the following 20260708133000_product_ops migration to create the tables cleanly.
