export const EXTENSION_ID = process.env.NEXT_PUBLIC_PAIDPOLITELY_EXTENSION_ID?.trim() ?? "";

export const EXTENSION_STORE_URL = process.env.NEXT_PUBLIC_PAIDPOLITELY_EXTENSION_STORE_URL?.trim() ?? "";

export const BRIDGE_REQUEST = "PAIDPOLITELY_EXTENSION_BRIDGE_REQUEST";

export const BRIDGE_RESPONSE = "PAIDPOLITELY_EXTENSION_BRIDGE_RESPONSE";
